2018-5-21 14:18:24
Unable to connect to the remote server
   at System.Net.HttpWebRequest.GetResponse()
   at LY.Exam.Common.WebUtils.DoGet(String url, IDictionary`2 parameters)
   at LY.Exam.BLL.UserLoginBLL.GetVersion()
   at LY.Exam.LoginWindow.GetLatestVersion()
套接字操作尝试一个无法连接的主机。 47.100.65.143:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
2018-5-21 14:18:27
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
Unable to connect to the remote server
   at System.Net.HttpWebRequest.GetResponse()
   at LY.Exam.Common.WebUtils.DoGet(String url, IDictionary`2 parameters)
   at LY.Exam.BLL.UserLoginBLL.GetListExam()
   at LY.Exam.LoginWindow.<>c.<Window_Loaded>b__7_1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
套接字操作尝试一个无法连接的主机。 47.100.65.143:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
